### ISSUE TITLE
vrchat errors // cannot initialize twice

### ISSUE THREAD

**Issue by untuned** [KaleidonKep99/Keppy-s-Synthesizer#151]
**Problem**
VRChat shows an error when loading, something with OmniMIDI.

**Steps to reproduce**
1. Install OmniMidi
2. Open VRChat

**Expected behavior**
No error window.

**Screenshots/Videos**
![error](https://i.untuned.us/u/YBHtvKiGsA.png)

**Environment**
```
OmniMIDI Information Dialog

== Driver info =================================================
Driver version: 8.1.0
BASS version: 2.4.14 (Revision 18)
BASSMIDI version: 2.4.12 (Revision 6)
Compiled on: 1.60.0 (Revision 0)

== Windows installation info ===================================
Name: Windows 10 Pro (64-bit)
Version: Version 1903 (Release 18362, Revision 356)

== Computer info ===============================================
Processor: AMD Ryzen 7 2700 Eight-Core Processor           (x64)
Processor info: 8 cores and 16 threads, running at 3.40GHz
Graphics card: NVIDIA GeForce GTX 1060 3GB
Graphics card info: 3072MB VRAM, driver version 26.21.14.3086

================================================================
End of info. Got them on 9/12/2019 7:19:02 PM.
```

**Additional context**
No idea why this happens.

**Comment by KaleidonKep99** [comment]
Add VRChat to the blacklist.

Steps:
1. Open the OmniMIDI configurator
2. Click File
3. Go to the blacklist manager
4. Add VRChat

**Comment by KaleidonKep99** [comment]
I could actually remove the message when an application opens the driver twice, but I left it to allow developers to see if their program is misbehaving with WinMM.
