### ISSUE TITLE
little bug

### ISSUE THREAD

**Issue by ZmanGamer** [KaleidonKep99/Keppy-s-Synthesizer#63]
today i have experienced crackly audio on keppys synthesizer

**Comment by ZmanGamer** [comment]
its my speakers lol not the cable its my speakers wearing out

**Comment by KaleidonKep99** [comment]
What's the point of this topic?

**Comment by ZmanGamer** [comment]
no it wasnt a bug lol it was my windows volume was 100 lol

**Comment by KaleidonKep99** [comment]
Increase the buffer size.
